# Generated by Django 5.0.9 on 2025-12-11 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SellerAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "platform",
                    models.CharField(
                        choices=[("limitless", "Limitless"), ("boostyfi", "BoostyFi")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("target_user_id", models.IntegerField(db_index=True)),
                ("wallet_address", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                (
                    "seller",
                    models.ForeignKey(
                        limit_choices_to={"is_seller": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seller_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Seller Assignment",
                "verbose_name_plural": "Seller Assignments",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["platform", "target_user_id"],
                        name="core_seller_platfor_db11fd_idx",
                    )
                ],
                "unique_together": {("seller", "platform", "target_user_id")},
            },
        ),
    ]
