# Generated by Django 5.0.9 on 2025-12-11 10:47

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LimitlessUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("original_id", models.IntegerField(db_index=True, unique=True)),
                (
                    "username",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("password_hash", models.CharField(blank=True, max_length=255)),
                (
                    "referral_code",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("referral_code_confirmed", models.BooleanField(default=False)),
                ("wallet", models.CharField(blank=True, db_index=True, max_length=255)),
                ("is_superuser", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_blocked", models.BooleanField(default=False)),
                ("date_joined", models.DateTimeField(blank=True, null=True)),
                ("parent_changed_at", models.DateTimeField(blank=True, null=True)),
                ("original_lft", models.IntegerField(blank=True, null=True)),
                ("original_rght", models.IntegerField(blank=True, null=True)),
                ("original_tree_id", models.IntegerField(blank=True, null=True)),
                ("original_level", models.IntegerField(blank=True, null=True)),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="limitless.limitlessuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Limitless User",
                "verbose_name_plural": "Limitless Users",
                "ordering": ["original_id"],
            },
        ),
        migrations.CreateModel(
            name="LimitlessPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("original_id", models.IntegerField(db_index=True, unique=True)),
                (
                    "buyer_original_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "amount_usdt",
                    models.DecimalField(decimal_places=6, default=0, max_digits=20),
                ),
                (
                    "tx_hash",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("block_number", models.BigIntegerField(blank=True, null=True)),
                ("contract_address", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("referral_system_status", models.IntegerField(blank=True, null=True)),
                ("pack_id", models.IntegerField(blank=True, null=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to="limitless.limitlessuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Limitless Purchase",
                "verbose_name_plural": "Limitless Purchases",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LimitlessEarning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("original_id", models.IntegerField(db_index=True, unique=True)),
                (
                    "recipient_original_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "buyer_original_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "purchase_original_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "earning_type",
                    models.CharField(
                        choices=[
                            ("NETWORK", "Network"),
                            ("BONUS_POOL", "Bonus Pool"),
                            ("LEGENDS_POOL", "Legends Pool"),
                        ],
                        db_index=True,
                        default="NETWORK",
                        max_length=50,
                    ),
                ),
                ("level", models.IntegerField(blank=True, null=True)),
                (
                    "percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "amount_usdt",
                    models.DecimalField(decimal_places=6, default=0, max_digits=20),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("WITHDRAWN", "Withdrawn"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("is_grace_period", models.BooleanField(default=False)),
                ("recipient_was_active", models.BooleanField(default=True)),
                ("compression_applied", models.BooleanField(default=False)),
                ("original_level", models.IntegerField(blank=True, null=True)),
                ("shares_count", models.IntegerField(blank=True, null=True)),
                ("distribution_id", models.IntegerField(blank=True, null=True)),
                (
                    "purchase",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="earnings",
                        to="limitless.limitlesspurchase",
                    ),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="earnings_generated",
                        to="limitless.limitlessuser",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="earnings",
                        to="limitless.limitlessuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Limitless Earning",
                "verbose_name_plural": "Limitless Earnings",
                "ordering": ["-created_at"],
            },
        ),
    ]
