# Generated by Django 5.0.9 on 2025-12-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limitless', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('export_id', models.IntegerField(db_index=True, unique=True, verbose_name='Export ID')),
                ('main_wallet', models.CharField(db_index=True, max_length=255, verbose_name='Main Wallet')),
                ('subwallets', models.TextField(blank=True, verbose_name='Subwallets')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_verified', models.BooleanField(default=False, verbose_name='Email Verified')),
                ('is_seller', models.BooleanField(default=False, verbose_name='Seller')),
                ('preferred_language', models.CharField(blank=True, max_length=100, verbose_name='Preferred Language')),
                ('can_communicate_english', models.BooleanField(default=False, verbose_name='Can Communicate in English')),
                ('community_count', models.IntegerField(default=0, verbose_name='Community Count')),
                ('atla_balance', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='ATLA Balance')),
                ('rank', models.CharField(blank=True, max_length=50, verbose_name='Rank')),
                ('has_lp', models.BooleanField(default=False, verbose_name='Has LP')),
                ('lp_shares', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='LP Shares')),
                ('has_chs', models.BooleanField(default=False, verbose_name='Has CHS')),
                ('ch_share', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='CH Share')),
                ('has_dsy', models.BooleanField(default=False, verbose_name='Has DSY')),
                ('dsy_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='DSY Bonus')),
                ('bfi_atla', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='BFI ATLA')),
                ('bfi_jggl', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='BFI JGGL')),
                ('jggl', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='JGGL')),
                ('need_private_zoom_call', models.BooleanField(default=False, verbose_name='Need Private Zoom Call')),
                ('want_business_dev_access', models.BooleanField(default=False, verbose_name='Want Business Dev Access')),
                ('want_ceo_access', models.BooleanField(default=False, verbose_name='Want CEO Access')),
                ('telegram', models.CharField(blank=True, max_length=255, verbose_name='Telegram')),
                ('facebook', models.CharField(blank=True, max_length=255, verbose_name='Facebook')),
                ('whatsapp', models.CharField(blank=True, max_length=255, verbose_name='WhatsApp')),
                ('viber', models.CharField(blank=True, max_length=255, verbose_name='Viber')),
                ('line', models.CharField(blank=True, max_length=255, verbose_name='Line')),
                ('other_contact', models.TextField(blank=True, verbose_name='Other Contact')),
            ],
            options={
                'verbose_name': 'Wallet Profile',
                'verbose_name_plural': 'Wallet Profiles',
                'ordering': ['-export_id'],
            },
        ),
    ]
