# Generated by Django 5.0.9 on 2025-12-11 10:47

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BoostyFiUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("original_id", models.IntegerField(db_index=True, unique=True)),
                (
                    "username",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("password_hash", models.CharField(blank=True, max_length=255)),
                (
                    "referral_code",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("referral_code_confirmed", models.BooleanField(default=False)),
                (
                    "referral_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Influencer", "Influencer"),
                            ("KOL", "KOL"),
                            ("Daisy", "Daisy"),
                            ("MLM", "MLM"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("wallet", models.CharField(blank=True, db_index=True, max_length=255)),
                ("evm_address", models.CharField(blank=True, max_length=255)),
                ("tron_address", models.CharField(blank=True, max_length=255)),
                (
                    "locked_atla_balance",
                    models.DecimalField(decimal_places=18, default=0, max_digits=30),
                ),
                (
                    "unlocked_atla_balance",
                    models.DecimalField(decimal_places=18, default=0, max_digits=30),
                ),
                ("is_superuser", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_blocked", models.BooleanField(default=False)),
                ("date_joined", models.DateTimeField(blank=True, null=True)),
                ("parent_changed_at", models.DateTimeField(blank=True, null=True)),
                ("original_lft", models.IntegerField(blank=True, null=True)),
                ("original_rght", models.IntegerField(blank=True, null=True)),
                ("original_tree_id", models.IntegerField(blank=True, null=True)),
                ("original_level", models.IntegerField(blank=True, null=True)),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="boostyfi.boostyfiuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "BoostyFi User",
                "verbose_name_plural": "BoostyFi Users",
                "ordering": ["original_id"],
            },
        ),
        migrations.CreateModel(
            name="BoostyFiPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("original_id", models.IntegerField(db_index=True, unique=True)),
                (
                    "buyer_original_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=6, default=0, max_digits=20),
                ),
                (
                    "full_amount",
                    models.DecimalField(decimal_places=6, default=0, max_digits=20),
                ),
                (
                    "discount_rate",
                    models.DecimalField(decimal_places=4, default=0, max_digits=5),
                ),
                (
                    "tx_hash",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("block_number", models.BigIntegerField(blank=True, null=True)),
                ("contract_address", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("CRYPTO", "Crypto"),
                            ("PAYID", "PayID"),
                            ("CARD", "Card"),
                        ],
                        db_index=True,
                        default="CRYPTO",
                        max_length=20,
                    ),
                ),
                ("referral_system_status", models.IntegerField(blank=True, null=True)),
                ("jggl_pack_id", models.IntegerField(blank=True, null=True)),
                ("atla_pack_id", models.IntegerField(blank=True, null=True)),
                ("paylink_invoice_id", models.CharField(blank=True, max_length=255)),
                ("paylink_reference_id", models.CharField(blank=True, max_length=255)),
                (
                    "buyer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to="boostyfi.boostyfiuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "BoostyFi Purchase",
                "verbose_name_plural": "BoostyFi Purchases",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BoostyFiEarning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("original_id", models.IntegerField(db_index=True, unique=True)),
                (
                    "user_original_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "buyer_original_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "purchase_original_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "earning_type",
                    models.CharField(
                        choices=[("NETWORK", "Network")],
                        db_index=True,
                        default="NETWORK",
                        max_length=50,
                    ),
                ),
                ("generation_level", models.IntegerField(blank=True, null=True)),
                (
                    "percentage",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=6, default=0, max_digits=20),
                ),
                (
                    "referral_pool",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=20, null=True
                    ),
                ),
                (
                    "referral_system_type",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "Influencer"), (2, "KOL"), (3, "MLM")],
                        db_index=True,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("WITHDRAWN", "Withdrawn"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "ppv",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=20, null=True
                    ),
                ),
                (
                    "tv",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=20, null=True
                    ),
                ),
                ("tier", models.IntegerField(blank=True, null=True)),
                ("qualification_reason", models.CharField(blank=True, max_length=255)),
                (
                    "tx_amount",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=20, null=True
                    ),
                ),
                (
                    "rpr",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("calculated_at", models.DateTimeField(blank=True, null=True)),
                ("is_sponsor_earning", models.BooleanField(default=False)),
                (
                    "sponsor_withhold_amount",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=20, null=True
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="earnings",
                        to="boostyfi.boostyfipurchase",
                    ),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="earnings_generated",
                        to="boostyfi.boostyfiuser",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="earnings",
                        to="boostyfi.boostyfiuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "BoostyFi Earning",
                "verbose_name_plural": "BoostyFi Earnings",
                "ordering": ["-created_at"],
            },
        ),
    ]
